Repository nuodb/nuodb-collector, pull requests merged in 2020-11, with the labels that each got.

#10 Allow for Admin Process Collector Daemons and silence error messages
  README.md
  docker-compose.yml
  nuocd/nuodb_adminquery.py
  nuocd/nuodb_threads.py
Labels: enhancement

#12 Add documentation for Kubernetes deployment
  README.md
Labels: documentation

#15 NuoDB Collector readme page updates and enhancements
  README.md
Labels: documentation

#16 Add nuodocker --servers-ready-timeout to Docker Compose
  docker-compose.yml
Labels: meta
